ISTART: 1
ICHARG: 2
ENCUT: 520
ISMEAR: 0
SIGMA: 0.05
ISPIN: 2
PREC: Accurate
EDIFF: 1E-06
ADDGRID: True
LREAL: Auto
ALGO: Fast
GGA: PE
IBRION: 5
NSW: 1
EDIFFG: -0.03
ISIF: 2
SYMPREC: 1E-8
POTIM: 0.015
NFREE: 2
