SYSTEM: matgen-relax
ISTART: 0
ISPIN: 2
LREAL: F
ENCUT: 520
PREC: Accurate
ADDGRID: T
NPAR: 4
NBLOCK: 1
INIWAV: 1
ISMEAR: 0 
SIGMA: 0.05
ALGO: Normal
NELM: 60
NELMIN: 6
EDIFF: 1E-05
NSW: 40
IBRION: 2
ISIF: 3
EDIFFG: -1E-03
POTIM: 0.5
LCORR: T
SYMPEREC: 1E-6
