SYSTEM: matgen-scf
ISTART: 0
ISPIN: 2
SYMPEREC: 1E-6
LREAL: F
ENCUT: 520
PREC: Accurate
LWAVE: T
LCHARG: T
ADDGRID: T
NPAR: 4
NBLOCK: 1
INIWAV: 1
ISMEAR: 0 
SIGMA: 0.05
ALGO: Normal
NELM: 140
NELMIN: 6
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 2
EDIFFG: -1E-02
POTIM: 0.05
LCORR: T
WEIMIN: 0
LAECHG: T
LORBIT: 11
