SYSTEM: matgen-spin-test
ISTART: 0
ISPIN: 2
LREAL: Auto
ENCUT: 520
PREC: Normal
NPAR: 4
ISMEAR: 0 
SIGMA: 0.05
ALGO: Fast
LDIAG: .T.
WEIMIN: 0
NELM: 60
NELMIN: 5
EDIFF: 1E-04
NSW: 0
IBRION: -1
ISIF: 0
EDIFFG: -1E-02
POTIM: 0.05
LCORR: .T.
SYMPEREC: 1E-6
