Uval:
    Ti: 4.4
    V: 2.7
    Cr: 3.5
    Mn: 4.0
    Fe: 4.6
    Co: 5.0
    Ni: 5.1
    Cu: 4.0
    Zn: 7.5
    Ga: 3.9
    Nb: 2.1
    Mo: 2.4
    Tc: 2.7
    Ru: 3.0
    Rh: 3.3
    Pd: 3.6
    Cd: 2.1
    In: 1.9
    Ta: 2.0
    W: 2.2
    Re: 2.4
    Os: 2.6
    Ir: 2.8
    Pt: 3.0
    La: 7.5
    Ce: 6.3
    Pr: 5.5
    Gd: 6.0
    Nd: 6.2
    Sm: 6.4
    Eu: 5.4
    Tm: 6.0
    Yb: 6.3
    Lu: 3.8
Uorbit:
    Ti: 2
    V: 2
    Cr: 2
    Mn: 2
    Fe: 2
    Co: 2
    Ni: 2
    Cu: 2
    Zn: 2
    Ga: 2
    Nb: 2
    Mo: 2
    Tc: 2
    Ru: 2
    Rh: 2
    Pd: 2
    Cd: 2
    In: 2
    Ta: 2
    W: 2
    Re: 2
    Os: 2
    Ir: 2
    Pt: 2
    La: 3
    Ce: 3
    Pr: 3
    Gd: 3
    Nd: 3
    Sm: 3
    Eu: 3
    Tm: 3
    Yb: 3
    Lu: 3